#define LED_GPIO_R GPIO_NUM_25
#define LED_GPIO_G GPIO_NUM_26
#define LED_GPIO_B GPIO_NUM_27

#define LEDC_TIMER LEDC_TIMER_0
#define LEDC_MODE LEDC_HIGH_SPEED_MODE
#define LEDC_CHANNEL_R LEDC_CHANNEL_0
#define LEDC_CHANNEL_G LEDC_CHANNEL_1
#define LEDC_CHANNEL_B LEDC_CHANNEL_2
#define LEDC_DUTY_RES LEDC_TIMER_8_BIT
#define LEDC_DUTY_MAX 255
